### PR TITLE
Provide alternative backends for caching of extracted content

### PR DESCRIPTION
**Pull request by tractorcow**

### CODE REVIEW

**Comment by tractorcow** [comment]
Since we probably can't always fill up our database with cached content. :D

**Comment by tractorcow** [comment]
I've added Flushable to the SS_Cache backend to allow cache clearing.

**Comment by tractorcow** [comment]
cc @chillu for review, please ;d

**Comment by chillu** [comment]
Nice! Can't find anything to complain about, so merging ;)

**Pull request merged**
