### PR TITLE
Move to new travis containerised infrastructure

### PR DESCRIPTION
**Pull request by dhensby**

### CODE REVIEW

**Comment by dhensby** [comment]
I don't think it's working, we're getting a skipped test

**Comment by chillu** [comment]
`pdftotext: command not found` in travis. @dhensby Any ideas?

**Comment by dhensby** [comment]
@chillu for some reason the binary we need doesn't seem to be installed - I've asked about this on the patch to travis

**Comment by dhensby** [comment]
Sorted :) @chillu @tractorcow

**Pull request merged**
